helm:
  parameters:
  - name: image.name
    value: asia.gcr.io/fast-audio-352608/core/kyberswap-interface
    forcestring: true
  - name: base-service.server.image.tag
    value: main-4b453be
    forcestring: true
