base-service:
  nameOverride: kyberswap-spa
  fullnameOverride: &name kyberswap-spa
  server:
    revisionHistoryLimit: 1
    image:
      repository: asia.gcr.io/fast-audio-352608/core/kyberswap-interface
      tag: main

    serviceAccount:
      create: true

    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 200Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 60
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 10
            periodSeconds: 20
          - type: Pods
            value: 2
            periodSeconds: 20
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 20
            periodSeconds: 10
          - type: Pods
            value: 5
            periodSeconds: 10
          selectPolicy: Max
    expose:
      port: "80"

    service:
      type: LoadBalancer
      port: 8080